### ISSUE TITLE
Reduce page overlap using two pass cluster algorithm

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Mapify#2]
Reported in #1

![image](https://github.com/user-attachments/assets/2e4dd3df-1754-446e-ba59-af92aedfe133)

**Comment by JamesBremner** [comment]
I think that the problem is that if just **one** waypoint is outside of the pages, then the size of **every** cluster is reduced.

My current thinking is that once only a few waypoints are missed, then the process of starting again with more clusters should be abandoned and a new approach should be applied focusing on the waypoints that are missed.

I propose using the same algorithm, but apply it only to the missed waypoints

**Comment by JamesBremner** [comment]
I implemented a simple, quick and dirty version of my proposal.  

The results look very hopeful - the overlaps are greatly reduced for almost every page and the number of pages required is reduce by 50% or so.

I will work on implementing this properly.

**Comment by JamesBremner** [comment]
I think the results are beginning to look reasonable

![image](https://github.com/user-attachments/assets/2ede22e1-09e1-4330-834e-32a943d6e44e)

What do you think?

**Comment by JamesBremner** [comment]
I have added the pseudo code for the two pass algorithm to the landing page

https://github.com/JamesBremner/Mapify/blob/main/README.md#algorithm

**Comment by DM-UK** [comment]
It does look a lot better. I was going to try a different approach, a modified k-means. After each iteration, in the calculation of the centroid, give greater value to points that are of that cluster but are outside of the page. Hopefully it moves the cluster towards points that are located outside of the page.

**Comment by JamesBremner** [comment]
> Hopefully it moves the cluster towards points that are located outside of the page

But it will also move the cluster so that some points that were covered will be uncovered.

**Comment by JamesBremner** [comment]
If you want to pursue your own development, you should open a new issue for it and either fork the repo or create your own development branch.

**Comment by JamesBremner** [comment]
@DM-UK I haven't heard from you in a day or so.  In the meantime I have worked on app usability, for details see https://github.com/JamesBremner/Mapify#gui

**Comment by DM-UK** [comment]
> > Hopefully it moves the cluster towards points that are located outside of the page
> 
> But it will also move the cluster so that some points that were covered will be uncovered.

I thought that if a cluster shifted towards an uncovered point, any points that it lost would be picked up by a neighboring cluster. But i'm not sure I've got the algorithm totally clear in my head yet (I'm not a professional developer, just a self taught hobbyist).

Do you have any suggestions to minimize overlap instead?

Here is a screenshot of a not quite perfect, but pretty good generation. This is just default k-means (with manual k number input) but shows under the right (rng) circumstances a good fit is possible.
![Untitled](https://github.com/user-attachments/assets/c351b82e-a54d-47b5-84d7-64d26f675719)

**Comment by JamesBremner** [comment]
I am curious:  what code are you running?  Your screenshot does not look like something produced by the Mapify application.  I support code that I have written or code from a pull request that I have accepted.  I cannot support code that I have never seen!

Here is a screenshot of the Mapify application

![image](https://github.com/user-attachments/assets/ab68b89a-b8f0-4012-af94-332b46482f63)

**Comment by DM-UK** [comment]
Unfortunately i'm a Java guy and have not used your app. I'm posting here as per your suggestion on stackoverflow. Apologies, if it's the wrong place.  Somewhere our discussion turned from algorithm specific to code specific.

**Comment by JamesBremner** [comment]
When you accepted the invitation to join this repo, I assumed that you wanted to use this app, or develop based on the code in this repo.

Please remove the screenshot - it has nothing to do with this app.  You may want to invite me to join YOUR repo, so that I might comment on your code.

**Comment by JamesBremner** [comment]
I have been working on a new algorithm where the first pass adds a new adjacent page to the last page which optimizes the number of new points covered without allowing any overlap.

This, of course, means that not all waypoints will be covered.  The missing waypoints are added in subsequent passes using the clustering algorithm.

First results look good, so I will close this issue.  The new algorithm is discussed in #3
