### ISSUE TITLE
Allow no overlaps on first pass

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Mapify#3]
- Create a page that covers the first waypoint and the maximum number of other waypoints
- FOR ever
   - add page adjacent to last page that covers the maximum number of new waypoints
   - IF last waypoint covered
        - BREAK 
 - Apply clustering algorithm to any remaining uncovered waypoints

**Comment by JamesBremner** [comment]
Here is the output from the first pass.  Few overlaps and few uncovered.

![image](https://github.com/user-attachments/assets/406e0a93-e97a-4bc9-bdcb-1b8f809e4795)

**Comment by JamesBremner** [comment]
Using cluster to cover the missed waypoints

![image](https://github.com/user-attachments/assets/5cb1bcb0-1245-4bfe-b347-f4b1bdb8323d)

**Comment by JamesBremner** [comment]
Released as v1.0.0.

You can download the executable from https://github.com/JamesBremner/Mapify/releases/tag/v1.0.0

Please test and let me know how you get on.

**Comment by DM-UK** [comment]
It all works greats thanks. If you're interested: https://github.com/DM-UK/MapMate

**Comment by JamesBremner** [comment]
Really?  All of it is absolutely great?  Your enthusiasm is a bit of a surprise!  

Did you actually test the Mapify application on some test cases?  Perhaps you could let me know a few more details of what you actually tested.

**Comment by JamesBremner** [comment]
Since there has been no response, I will close this issue and move on to the next feature: page rotation
